export { default as CheckIcon } from "./CheckIcon.vue"
export { default as GenderIcon } from "./GenderIcon.vue"
export { default as ManIcon } from "./ManIcon.vue"
export { default as WomanIcon } from "./WomanIcon.vue"
export { default as Loader } from "./Loader.vue"